# Generated by Django 5.1.2 on 2024-10-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_customuser_managers_rename_otps_customuser_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
